### ISSUE TITLE
Using this, how to analyze the color configuration under dark mode?

### ISSUE THREAD

**Issue by JohnSmithHY** [Timac/CARParser#1]
In dark mode, you can set multiple colors, such as color_ test, any light,dark。 With this example, I don't know how to parse car files.
such as Json:
  {
    "AssetType" : "Color",
    "Color components" : [
      0.45899999141693115,
      1,
      1,
      1
    ],
    "Colorspace" : "srgb",
    "Name" : "color_set",
    "NameIdentifier" : 4492,
    "Scale" : 1
  },
  {
    "Appearance" : "UIAppearanceDark",
    "AssetType" : "Color",
    "Color components" : [
      1,
      1,
      0.11299999803304672,
      1
    ],
    "Colorspace" : "srgb",
    "Name" : "color_set",
    "NameIdentifier" : 4492,
    "Scale" : 1
  }

**Comment by Timac** [comment]
I am not sure to fully understand the question. You have a .car file and would like to extract the colors for the various themes (light, dark, ...) using CARParser?

I think that in this case you should see  one `CUIThemeColorRendition` for each color. Something like:

```
csiHeader:
	 version: 1
	 renditionFlags: bitmapEncoding 0
	 width: 0
	 height: 0
	 scaleFactor: 0
	 pixelFormat: 0x0000
	 colorSpaceID: 1
	 modtime: 0
	 layout: Color
	 name: MyColor
	 tvlLength: 28
	 renditionLength: 48
	 tlv:
		 BlendModeAndOpacity: 0000000000000000
		 EXIFOrientation: 01000000

 Found Color 1.000000,0.000000,0.000000,0.500000 with colorspace ID 1
```

See https://blog.timac.org/2018/1018-reverse-engineering-the-car-file-format/ for more info.

In your json, it seems that you have one color with the name `color_set` and NameIdentifier `4492`. One color has no `Appearance` so it should be the default while the other is for dark mode with the `UIAppearanceDark` appearance.

Hopefully this helps.
